### PR TITLE
Fix basic notebook and running Linux.

### LINKED ISSUE #1: gke-notebook: spawning kernel failed
Hi,

I followed the steps at https://cloud.google.com/solutions/spawning-notebook-servers-on-gke-tutorial to setup the jupyter hub on GKE. After the step getting the URL, I was able to connect to the hub. However when I launch my kernel it fails:

1. If I select the basic kernel, it fails with:
```
Server requested
2020-12-02T00:30:51Z [Normal] Successfully assigned default/jupyter-feyu to XXXXXXXXXXXXXXXXXXXXX
2020-12-02T00:30:51Z [Normal] Container image "gcr.io/XXXXXXXXXXX/jupyter-mine-basic" already present on machine
2020-12-02T00:30:51Z [Normal] Created container notebook
2020-12-02T00:30:51Z [Normal] Started container notebook
Spawn failed: Server at http://XXXXXXXX:8080/user/feyu/ didn't respond in 30 seconds
```

2. If I select the tf2 kernel, the singluser server is launched, but I get a page not found (404) error on /user/feyu.

It seems like for 1), the issue is the docker image was misconfigured (e.g. the path to binary is incorrect?)
for 2), the user dispatch proxy of jupyterhub may be misconfigured. (Perhaps something wrong with the kubenates launcher)

However, I am quite new to GKE and at this point I don't know where to look for logs to debug this further. Any suggestions?

Thanks!

### PR DESCRIPTION
**Pull request by rainwoodman**
Fixes #1.

There is an associated proposal improvement for kubespanwer filed as https://github.com/jupyterhub/kubespawner/issues/462 while debugging this.

### CODE REVIEW

File: gke-hub-example/deploy/manually/10-set-variables.sh [hunk 1]
```diff
@@ -31,14 +31,14 @@ echo "--------------------------------"
 export ZONE="us-west1-b"
 
 # Whether to create a cluster with Workload Identity enabled.
-export WID="false"
+export WID="true"
```
Comment (m-mayran) [inline gke-hub-example/deploy/manually/10-set-variables.sh:34]: If we always create a Workload Identity enabled cluster as 20-.sh seems to suggest, I don't think we need this anymore, especially if we bring more identity related feature.

**Review by m-mayran — APPROVED** [review]

File: gke-hub-example/deploy/manually/10-set-variables.sh (hunk 1 above)
Comment (rainwoodman) [reply gke-hub-example/deploy/manually/10-set-variables.sh:34]: Indeed!
